_BASE_: msu_pid_r50_guide_cocopre_0.yaml
OUTPUT_DIR: "./output/msu_pid_r50_guide_cocopre_1/"
DATASETS:
  TRAIN: ('msu_pid_arabidopsis_train_coco_1',) # 396 images
  TEST: ('msu_pid_arabidopsis_val_coco_1',) # 72 images
  # TEST: ('msu_pid_arabidopsis_test_coco_1',) # 108 images
MODEL:
  MASK_FORMER:
    # for the embeddings
    GUIDE_FUNCTION_PATH: "./harmonic/guide_functions/msu_pid_arabidopsis_train_coco_1_emb_16.json"