_BASE_: komatsuna_rgb_r50_baseline_cocopre_0.yaml
OUTPUT_DIR: "./output/komatsuna_rgb_r50_baseline_cocopre_1/"
DATASETS:
  TRAIN: ('komatsuna_rgb_train_coco_1',) # 540 images
  TEST: ('komatsuna_rgb_val_coco_1',) # 180 images
  # TEST: ('komatsuna_rgb_test_coco_1',) # 180 images
